[package]
name = "invoice"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "0.5"
lopdf = "0.29.0"
jpeg-decoder = "0.3.0"
chrono = "0.4"