[package]
name = "ca_pdf"
version = "0.1.0"
edition = "2024"


[dependencies]
chromiumoxide = "0.5"
dotenv = "0.15"
surf = "2.3"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"