[package]
name = "wiki"
version = "0.1.0"
edition = "2024"

[dependencies]
chromiumoxide = "0.5"
dotenv = "0.15"
surf = "2.3" # HTTP client compatible with async-std
serde_json = "1.0"
async-std = { version = "1.12", features = ["unstable"] }
futures = "0.3"