[package]
name = "pdf-word"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-extract = "0.6.0"
docx-rs = "0.4.18-rc19"  # Using the available prerelease version
anyhow = "1.0"
regex = "1.7"
unicode-normalization = "0.1.22"